### ISSUE TITLE
Windows Support + Beats Studio Buds

### ISSUE THREAD

**Issue by ayaangrover** [kavishdevar/aln#2]
It would be great if support was available for Windows too, but for the beats studio buds.

**Comment by kavishdevar** [comment]
Hi!
Thank you for checking out this project.

Unfortunately, I have access to neither windows nor the beats studio buds. You can check out MagicPods which is a great (paid) app for Windows that supports many headphones.

If I can get the studio buds, I can put some efforts and make something for windows too.

**Comment by ayaangrover** [comment]
Alright, thanks!
